exclude:
    - 'app/styles/bourbon/**'
    - 'app/styles/bourbon/**/**'
    - 'app/styles/neat/**'
    - 'app/styles/neat/**/**'
    - 'app/styles/main.css'

# Default application configuration that all configurations inherit from.
# This is the same as the default config for the gem: https://github.com/causes/scss-lint/blob/master/config/default.yml
linters:
  BorderZero:
    enabled: true

  CapitalizationInSelector:
    enabled: true

  ColorKeyword:
    enabled: true

  Comment:
    enabled: true

  DebugStatement:
    enabled: true

  DeclarationOrder:
    enabled: true

  DeclaredName:
    enabled: true

  DuplicateProperty:
    enabled: true

  EmptyRule:
    enabled: true

  HexFormat:
    enabled: true

  IdWithExtraneousSelector:
    enabled: true

  Indentation:
    enabled: true
    width: 2

  LeadingZero:
    enabled: true

  PlaceholderInExtend:
    enabled: true

  Shorthand:
    enabled: true

  SingleLinePerSelector:
    enabled: true

  SortedProperties:
    enabled: false

  SpaceAfterComma:
    enabled: true

  SpaceAfterPropertyColon:
    enabled: true

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true

  StringQuotes:
    enabled: false

  TrailingSemicolonAfterPropertyValue:
    enabled: true

  UsageName:
    enabled: true

  ZeroUnit:
    enabled: true

  Compass::PropertyWithMixin:
    enabled: false